[package]
name = "scrape-packages"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
scraper = { version = "0.19.0", features = [] }
url = "2"
reqwest = "0.11"
thiserror = "1"
simplelog = "0.12.2"
log = "0.4"
